language: perl
sudo: false
dist: trusty
cache:
  ccache: true
  #directories:
  #  - $HOME/amd64
addons:
  apt:
    packages:
      - cmake
#     - libpcre2-dev

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20-thr"
  - "5.22-thr"
  - "5.24"
  - "5.24-thr"
  - "5.26"
  - "5.28-thr"
  - "dev"

# not run tag pushes
branches:
  except:
  - /^v?[0-9]+\.[0-9]+/

before_install:
  - mkdir $HOME/bin || true
  - ln -s `which true` $HOME/bin/cpansign
  #- wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pcre2/pcre2_10.22.orig.tar.gz
  #- tar xfz pcre2_10.22.orig.tar.gz
  #- cd pcre2-10.22
  - git clone --depth=1 git://github.com/rurban/pcre
  - cd pcre
  - CFLAGS=-fPIC cmake -DPCRE2_SUPPORT_JIT=ON -DCMAKE_INSTALL_PREFIX=$HOME/amd64 .
  - make -s -j4
  - make install
  - cd ..
  - eval $(curl https://travis-perl.github.io/init) --perl

script:
  - coverage-setup
  - perl Makefile.PL PREFIX=$HOME/amd64 && make test LDLOADLIBS="-L$HOME/amd64/lib -lpcre2-8"
  - coverage-report

install:
  - export AUTOMATED_TESTING=1 HARNESS_TIMER=1 AUTHOR_TESTING=0 RELEASE_TESTING=0
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs converage prereqs, if enabled
  - cpan-install Devel::CheckLib
  - cpan-install Class::XSAccessor Text::CSV_XS List::MoreUtils

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  fast_finish: true
  include:
    - perl: "5.24"
      env: COVERAGE=1 AUTHOR_TESTING=1 RELEASE_TESTING=1 # enables coverage+coveralls reporting
  allow_failures:
    - perl: "dev"
    - perl: "5.10"
    - perl: "5.24"
      env: COVERAGE=1 AUTHOR_TESTING=1 RELEASE_TESTING=1 # enables coverage+coveralls rep
